schema: "classroom50/repo-config/v1"
classroom: "cprog"
assignment: "i-know-flowchart"
owner:
  username: "Marco-Lund-Jensen"
  id: 322745085
  accepted_at: "2026-09-02T14:09:29Z"
source:
  owner: "geko-crooms"
  owner_id: 316422449
  repo: "i-know-flowchart"
  branch: "main"
